### ISSUE TITLE
Support embed CodePen in posts

### ISSUE THREAD

**Issue by wgao19** [CodingGirlsSG/30-days-of-css#5]
We're using a lot of CodePen pens so it'd be a good idea to support CodePen embed in our posts.

Luckily [Gatsby already has a plugin that supports that](https://github.com/weknowinc/gatsby-remark-codepen). Need to add it to our site and make sure everything works.

**Comment by taejs** [comment]
I' ll try to embed for this issue.

**Comment by taejs** [comment]
![image](https://user-images.githubusercontent.com/41318449/54254908-05bb8900-4599-11e9-96b2-b189c7b92480.png)
Now, codepen works on our site.

If just write down codepen URL on markdown files, and then codepen appears!

```
https://codepen.io/wgao19/pen/qLrvaB
```

just like that.
